name: Slack Newtwork Analysis

on:
  push:
    branches:
      - main

jobs:
  deploy_apps:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Images
        run: |
          docker build -t backend .
          docker build -t frontend .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Images
        run: |
          docker push backend
          docker push frontend

      - name: Deploy Apps to Server
        run: |
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }} "docker-compose up -d"
        working-directory: ./
        shell: bash
